### ISSUE TITLE
Netlify posts broken?

### ISSUE THREAD

**Issue by extricator** [flaviocopes/website-content#111]
Right now I'm looking for the post you made about hosting your own static blog using Hugo and I can't find it. I'm pretty sure you had a good one but can't find it in my bookmarks or using the search function. If I go here: https://flaviocopes.com/netlify/ the first sentence mentions the "netlify" tutorial but the url points to the same url you're currently on. Not sure if you got rid of that post, if so, can you point me to where it is here on github? Love your content. Thanks!

**Comment by flaviocopes** [comment]
Oh  thanks for opening this issue! I didn't know how, but I overwrote the original post with the netlify functions post. Restored! https://flaviocopes.com/netlify/
