### ISSUE TITLE
No longer see dark/light icon + other elements

### ISSUE THREAD

**Issue by extricator** [flaviocopes/website-content#114]
I can no longer see the moon dark/light icon. I can't pinpoint what but other website elements seem to be missing as well.

**Comment by flaviocopes** [comment]
I have removed it. I now use the `prefers-color-scheme` setting to set the theme https://flaviocopes.com/dark-mode/

**Comment by extricator** [comment]
Maybe I'm wrong but isn't that browser property only affected by the OS dark mode setting? If so, I'll consider this a regression since some OSes don't have a dark mode setting yet (think Linux). I tried to find a way to change it via a setting in Firefox and didn't have any luck. I'm sure there's an about:config setting that could be tweaked but I think your users shouldn't rely on that to get dark mode. Although I guess that would depend on how many Linux visitors your site gets.

**Comment by flaviocopes** [comment]
Let's see, I am sure browsers will find a way to implement this correctly if the OS does not provide the functionality (e.g. I think Firefox themes  will allow this)
