### ISSUE TITLE
Potential error in "How to get yesterday's date using JavaScript"

### ISSUE THREAD

**Issue by victor-homyakov** [flaviocopes/website-content#130]
Script example in https://flaviocopes.com/how-to-get-yesterday-date-javascript/ may behave unexpectedly at midnight - there is a chance that `today` and `yesterday` will point to different dates:

```js
const today = new Date() // 15 Oct 2019 23:59:59
const yesterday = new Date() // 16 Oct 2019 00:00:00

yesterday.setDate(yesterday.getDate() - 1)

today.toDateString() // "Tue Oct 15 2019"
yesterday.toDateString() // "Tue Oct 15 2019"
```

To avoid this and similar errors, construct `yesterday` from current date object

```js
const today = new Date()
const yesterday = new Date(today)
```

In general, when working with date calculations, there should be only one point where current date/time is retrieved. Time goes by and there's no guarantee that two consequent `new Date(); new Date();` will return the same time.

P.S. There's even no guarantee that they will return **the same or increasing** time, because system clock may be adjusted backwards in the moment between our calls. Monotonic clock is accessed from JavaScript via `performance.now()` in browsers and via `process.hrtime()` in Node.

**Comment by flaviocopes** [comment]
Good point Victor, thanks for telling me! I fixed the example 👍🏼
