### ISSUE TITLE
Incorrect advice for solving issues with global npm install

### ISSUE THREAD

**Issue by DeltaF1** [flaviocopes/website-content#149]
[This article](https://flaviocopes.com/npm-fix-missing-write-access-error/) gives incorrect and potentially dangerous advice about how to solve npm global installation errors. The more correct way to deal with the permission errors is to create a user-owned directory for global modules, as detailed in [the npm docs](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally).

**Comment by flaviocopes** [comment]
(added a note to the article)
