### ISSUE TITLE
HttpLink causing cors errors: createHttpLink solved them

### ISSUE THREAD

**Issue by adriancorcoran** [flaviocopes/website-content#3]
First of all, brilliant tutorial - once of the clearest and easiest to use that I have found. 

I did run into one small issue, using `HttpLink` caused cors errors on my machine when trying to connect to GitHub.

I changed to using `createHttpLink` and everything seemed to work fine :)

The two changes I needed were:

**Line 4: change**
```
import { HttpLink } from 'apollo-link-http'
```
to
```
import { createHttpLink } from "apollo-link-http";
```
and 

**Line 12: change**
```
const httpLink = new HttpLink({ uri: 'https://api.github.com/graphql' })
```
to
```
const httpLink = new createHttpLink({ uri: 'https://api.github.com/graphql' })
```

Maybe it was just me, but thought I'd let you know. Thanks again for a great tutorial :)

**Comment by flaviocopes** [comment]
Hi Adrian thanks for the feedback! It seems it's working fine for me, in both cases. 

Although it should probably be 

```
const httpLink = createHttpLink({ uri: 'https://api.github.com/graphql' })
```

without `new`? But works the same.

Anyway it seems from https://stackoverflow.com/questions/56663103/differences-between-new-httplink-and-createhttplink-from-package-apollo-link-htt and https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http that `new HttpLink()` is never used in the official docs, not sure where I got that from! 

Going to change the post with your proposed syntax, thanks again!

**Comment by adriancorcoran** [comment]
No prob Flavio :)

**Comment by flaviocopes** [comment]
Fixed in https://github.com/flaviocopes/website-content/commit/6046ea5a9499d03c2fa7f093dc619378d4cd50d0
