### ISSUE TITLE
Promise map example doesn't work.

### ISSUE THREAD

**Issue by inorganik** [flaviocopes/website-content#53]
The example here does not provide the desired result: https://github.com/flaviocopes/website-content/blob/content/post/javascript/javascript-async-await-array-map/index.md

The resulting log is a promise object - because async functions don't return the resolved value.

Here is a stackblitz that runs your code from this page: https://stackblitz.com/edit/typescript-tky1fv

Notice the log which is just a Promise object.

**Comment by deadcoder0904** [comment]
Submitted a PR #121

**Comment by flaviocopes** [comment]
Fixed by https://github.com/flaviocopes/website-content/pull/121 !
