### ISSUE TITLE
Small mistake in file

### ISSUE THREAD

**Issue by luisbausalopez** [flaviocopes/website-content#68]
On the file:
https://github.com/flaviocopes/website-content/blob/content/post/javascript/javascript-global-object/index.md

on line 241 it says 

// "http%3A%2F%2Fflaviocopes.com%2F%20hey!%2F"

where it should say

// "http%3A%2F%2Fwww.example.org%2Fa%20file%20with%20spaces.html"

**Comment by flaviocopes** [comment]
Oh thanks! Fixed :) https://github.com/flaviocopes/website-content/commit/6596a49d43be03e50257d5339918ac8ffad42a00
