### ISSUE TITLE
Wrong Content About Promise

### ISSUE THREAD

**Issue by muradsofiyev** [flaviocopes/website-content#9]
Hello.
ES6 Job Queue Section in https://flaviocopes.com/javascript-event-loop/ page is wrong about Promise. 
You say about Promise - "It’s a way to execute the result of an async function as soon as possible, rather than being put at the end of the call stack." 
This is absolutely false. 
Promise help to us escape callback hell not run async function as soon as possible. 
Please change this text.

**Comment by flaviocopes** [comment]
That description refers to Job Queues, not to promises.
